type RoomTier = "free" | "premium" | "super_premium";
export type UiLanguage = "cs" | "en" | "es" | "de" | "fr" | "pt-BR";
export type GameLanguage = "cs" | "en" | "es" | "de" | "fr" | "pt-BR" | "id" | "tr" | "pl" | "it";

export const UI_TEXT = {
  cs: {
    room: "Místnost",
    signedIn: "Přihlášen",
    notSignedIn: "Nepřihlášen",
    bossRoom: "Ty platíš, ty jsi šéf této místnosti!",
    likeApp: "Líbí se vám aplikace?",
    ratingUnavailable: "Hodnocení bude dostupné po vydání aplikace na Google Play.",
    newGame: "Nová hra",
    rules: "Pravidla",
    copyLink: "Kopírovat odkaz",
    share: "Sdílet",
    disconnect: "Odpojit",
    gameLanguage: "Jazyk hry",
    diacriticsOptional: "Odpovědi jsou platné i bez diakritiky.",
    joinGame: "Připojit se do hry",
    yourName: "Tvoje jméno",
    join: "Připojit se",
    startGame: "Spustit hru",
    gameSettings: "Nastavení hry",
    timeLimit: "Časový limit",
    noTimeLimit: "Bez limitu",
    roundCount: "Počet kol",
    unlimitedRounds: "Bez omezení",
    roundsCountSuffix: "kol",
    gameSettingsSaveErrorPrefix: "❌ nastavení hry",
    availableLetters: "Výběr písmen",
    players: "Hráči",
    waitingPlayers: "Čekající hráči",
    roomCategories: "Kategorie místnosti",
    basicCategories: "Základní kategorie",
    extendedCategories: "Rozšířené kategorie",
    customCategories: "Vlastní kategorie",
    categoryOrder: "Pořadí kategorií",
    playing: "Hrajeme",
    drawAgain: "Losovat znovu",
    scoring: "Bodování",
    submitted: "Odesláno",
    playersAnswers: "Odpovědi hráčů",
    player: "Hráč",
    totalPoints: "Body celkem",
    round: "Kolo",
    myScoring: "Moje bodování",
    submitScoring: "Odeslat bodování",
    newRound: "Nové kolo",
    finishGame: "Ukončit hru a zobrazit konečné výsledky",
    finalResults: "Konečné výsledky",
    position: "Pořadí",
    gameFinishedMessage: "✅ Hra ukončena. Tady jsou konečné výsledky.",
    finishGameErrorPrefix: "❌ ukončení hry",
    letterDrawn: "✅ vylosováno",
    drawingAgain: "… losujeme znovu",
    drawingNextRound: "… losujeme další kolo",
    drawingLetter: "… losujeme",
    changePlayerAfterScoring: "Hráče můžeš změnit až po ukončení bodování.",
    changingPlayerErrorPrefix: "❌ změna hráče",
    previousPlayerRemoved: "ℹ️ Původní hráč byl z tohoto zařízení odebrán. Zadej jiné jméno.",
    disconnectedRoomCleared: "✅ odpojeno, místnost vyčištěna",
    disconnected: "✅ odpojeno",
    joinNameFirst: "❗ nejdřív se připoj jménem",
    savingScoresErrorPrefix: "❌ uložení bodů",
    stopAfterFields: "STOP půjde zmáčknout až po vyplnění všech polí.",
    minTwoChars: "Každé pole musí mít alespoň dvě písmena.",
    mustStartWithLetter: "Každé pole musí začínat vylosovaným písmenem.",
    waitingToJoin: "⏳ Čekáš na připojení. Do hry tě pustíme od dalšího kola.",
    enterNameAnswers: "Přihlaš se jménem nahoře, abys mohl psát odpovědi.",
    statusSubmitted: " – odeslal",
    statusWaiting: " – čekáme",
    hideRoundHistory: "Skrýt historii kol",
    showRoundHistory: "Zobrazit historii kol",
    noRoundScores: "Zatím nejsou uložené body za žádné kolo.",
    zeroPoints: "0 bodů",
    fivePoints: "5 bodů",
    tenPoints: "10 bodů",
    minusFivePoints: "-5 bodů",
    minusTenPoints: "-10 bodů",
    scoringSubmitted: "✅ Bodování odesláno. Případní čekající hráči se automaticky připojí po stisknutí tlačítka Nové kolo.",
    enterNameScoring: "Přihlaš se jménem nahoře, abys mohl odeslat bodování.",
    waitingForAllPlayers: "Čekáme na všechny hráče…",
    customCategoryPrefix: "Vlastní kategorie",
    removeCustomCategory: "Odebrat vlastní kategorii",
    addCustomCategory: "+ Přidat vlastní kategorii",
    maxCustomCategories: "Maximum je 5 vlastních kategorií.",
    premiumLockedCategoryOfferIntro: "Při zakoupení rozšířené kategorie se ti automaticky odemkne možnost volby počtu a pořadí kategorií, se kterými chceš hrát.",
    superPremiumUpsellBefore: "Nebo si kup",
    superPremiumLinkText: "Super Premium",
    superPremiumUpsellAfter: "a budeš mít k dispozici možnost volby počtu a pořadí kategorií, všechny rozšířené kategorie plus 5 vlastních.",
    changePlayerOnDevice: "Změnit hráče na tomto zařízení",
    waitingPlayerNextRound: "připojí se od dalšího kola",
      freeLimitTitle: "Free limit dosažen",
      freeLimitText: "Ve Free verzi máš 3 kola. Pro pokračování přejdi na Premium, nebo si dobrovolně pusť reklamu a odemkni další 3 kola.",
      freeUpgradeButton: "Získat Premium",
      freeRewardButton: "Sledovat reklamu a odemknout další 3 kola",
      backHome: "Zpět na hlavní stránku",
      freeRewardUnlocked: "✅ Další 3 kola jsou odemčená.",
      freeLimitReachedMessage: "Free limit dosažen. Pro pokračování zvol Premium nebo rewarded reklamu.",
  },
  en: {
    room: "Room",
    signedIn: "Signed in",
    notSignedIn: "Not signed in",
    bossRoom: "You paid, so you are the boss of this room!",
    likeApp: "Do you like the app?",
    ratingUnavailable: "Rating will be available after the app is released on Google Play.",
    newGame: "New game",
    rules: "Rules",
    copyLink: "Copy link",
    share: "Share",
    disconnect: "Disconnect",
    gameLanguage: "Game language",
    diacriticsOptional: "Answers are valid even without diacritics.",
    joinGame: "Join the game",
    yourName: "Your name",
    join: "Join",
    startGame: "Start game",
    gameSettings: "Game settings",
    timeLimit: "Time limit",
    noTimeLimit: "No limit",
    roundCount: "Number of rounds",
    unlimitedRounds: "Unlimited",
    roundsCountSuffix: "rounds",
    gameSettingsSaveErrorPrefix: "❌ game settings",
    availableLetters: "Available letters",
    players: "Players",
    waitingPlayers: "Waiting players",
    roomCategories: "Room categories",
    basicCategories: "Basic categories",
    extendedCategories: "Extended categories",
    customCategories: "Custom categories",
    categoryOrder: "Category order",
    playing: "Playing",
    drawAgain: "Draw again",
    scoring: "Scoring",
    submitted: "Submitted",
    playersAnswers: "Players’ answers",
    player: "Player",
    totalPoints: "Total points",
    round: "Round",
    myScoring: "My scoring",
    submitScoring: "Submit scoring",
    newRound: "New round",
    finishGame: "Finish game and show final results",
    finalResults: "Final results",
    position: "Rank",
    gameFinishedMessage: "✅ Game finished. Here are the final results.",
    finishGameErrorPrefix: "❌ finishing game",
    letterDrawn: "✅ letter drawn",
    drawingAgain: "… drawing again",
    drawingNextRound: "… drawing a letter for the next round",
    drawingLetter: "… drawing a letter",
    changePlayerAfterScoring: "You can change the player only after scoring has finished.",
    changingPlayerErrorPrefix: "❌ changing player",
    previousPlayerRemoved: "ℹ️ The previous player was removed from this device. Enter a different name.",
    disconnectedRoomCleared: "✅ disconnected, room cleared",
    disconnected: "✅ disconnected",
    joinNameFirst: "❗ join with a name first",
    savingScoresErrorPrefix: "❌ saving scores",
    stopAfterFields: "You can press STOP after completing every field.",
    minTwoChars: "Every field must contain at least two characters.",
    mustStartWithLetter: "Every answer must begin with the drawn letter.",
    waitingToJoin: "⏳ You are waiting to join. You will enter the game from the next round.",
    enterNameAnswers: "Enter your name above to submit answers.",
    statusSubmitted: " – submitted",
    statusWaiting: " – waiting",
    hideRoundHistory: "Hide round history",
    showRoundHistory: "Show round history",
    noRoundScores: "No round scores have been saved yet.",
    zeroPoints: "0 points",
    fivePoints: "5 points",
    tenPoints: "10 points",
    minusFivePoints: "-5 points",
    minusTenPoints: "-10 points",
    scoringSubmitted: "✅ Scoring submitted. Waiting players will automatically join after pressing New round.",
    enterNameScoring: "Enter your name above to submit scoring.",
    waitingForAllPlayers: "Waiting for all players…",
    customCategoryPrefix: "Custom category",
    removeCustomCategory: "Remove custom category",
    addCustomCategory: "+ Add custom category",
    maxCustomCategories: "The maximum is 5 custom categories.",
    premiumLockedCategoryOfferIntro: "Buying an extended category automatically unlocks the option to choose the number and order of categories you want to play with.",
    superPremiumUpsellBefore: "Or buy",
    superPremiumLinkText: "Super Premium",
    superPremiumUpsellAfter: "and you will get category count and order selection, all extended categories, plus 5 custom categories.",
    changePlayerOnDevice: "Change player on this device",
    waitingPlayerNextRound: "will join from the next round",
      freeLimitTitle: "Free limit reached",
      freeLimitText: "The Free version includes 3 rounds. To continue, upgrade to Premium or choose to watch an ad and unlock 3 more rounds.",
      freeUpgradeButton: "Get Premium",
      freeRewardButton: "Watch an ad and unlock 3 more rounds",
      backHome: "Back to homepage",
      freeRewardUnlocked: "✅ 3 more rounds are unlocked.",
      freeLimitReachedMessage: "Free limit reached. Choose Premium or a rewarded ad to continue.",
  },
  es: {
    room: "Sala",
    signedIn: "Conectado",
    notSignedIn: "No conectado",
    bossRoom: "¡Tú pagas, tú mandas en esta sala!",
    likeApp: "¿Te gusta la aplicación?",
    ratingUnavailable: "La valoración estará disponible después de publicar la aplicación en Google Play.",
    newGame: "Nueva partida",
    rules: "Reglas",
    copyLink: "Copiar enlace",
    share: "Compartir",
    disconnect: "Desconectar",
    gameLanguage: "Idioma del juego",
    diacriticsOptional: "Las respuestas también son válidas sin tildes ni acentos.",
    joinGame: "Unirse al juego",
    yourName: "Tu nombre",
    join: "Unirse",
    startGame: "Iniciar partida",
    gameSettings: "Ajustes de partida",
    timeLimit: "Límite de tiempo",
    noTimeLimit: "Sin límite",
    roundCount: "Número de rondas",
    unlimitedRounds: "Sin límite",
    roundsCountSuffix: "rondas",
    gameSettingsSaveErrorPrefix: "❌ ajustes de partida",
    availableLetters: "Letras disponibles",
    players: "Jugadores",
    waitingPlayers: "Jugadores en espera",
    roomCategories: "Categorías de la sala",
    basicCategories: "Categorías básicas",
    extendedCategories: "Categorías ampliadas",
    customCategories: "Categorías propias",
    categoryOrder: "Orden de categorías",
    playing: "Jugando",
    drawAgain: "Sortear otra vez",
    scoring: "Puntuación",
    submitted: "Enviado",
    playersAnswers: "Respuestas de los jugadores",
    player: "Jugador",
    totalPoints: "Puntos totales",
    round: "Ronda",
    myScoring: "Mi puntuación",
    submitScoring: "Enviar puntuación",
    newRound: "Nueva ronda",
    finishGame: "Terminar partida y mostrar resultados finales",
    finalResults: "Resultados finales",
    position: "Puesto",
    gameFinishedMessage: "✅ Partida terminada. Aquí están los resultados finales.",
    finishGameErrorPrefix: "❌ al terminar la partida",
    letterDrawn: "✅ letra sorteada",
    drawingAgain: "… sorteando de nuevo",
    drawingNextRound: "… sorteando una letra para la siguiente ronda",
    drawingLetter: "… sorteando una letra",
    changePlayerAfterScoring: "Puedes cambiar de jugador solo después de terminar la puntuación.",
    changingPlayerErrorPrefix: "❌ cambio de jugador",
    previousPlayerRemoved: "ℹ️ El jugador anterior se eliminó de este dispositivo. Introduce otro nombre.",
    disconnectedRoomCleared: "✅ desconectado, sala limpiada",
    disconnected: "✅ desconectado",
    joinNameFirst: "❗ primero únete con tu nombre",
    savingScoresErrorPrefix: "❌ guardando puntos",
    stopAfterFields: "Puedes pulsar STOP después de completar todos los campos.",
    minTwoChars: "Cada campo debe tener al menos dos caracteres.",
    mustStartWithLetter: "Cada respuesta debe empezar con la letra sorteada.",
    waitingToJoin: "⏳ Estás esperando para unirte. Entrarás en el juego desde la siguiente ronda.",
    enterNameAnswers: "Introduce tu nombre arriba para enviar respuestas.",
    statusSubmitted: " – enviado",
    statusWaiting: " – esperando",
    hideRoundHistory: "Ocultar historial de rondas",
    showRoundHistory: "Mostrar historial de rondas",
    noRoundScores: "Todavía no hay puntos guardados de ninguna ronda.",
    zeroPoints: "0 puntos",
    fivePoints: "5 puntos",
    tenPoints: "10 puntos",
    minusFivePoints: "-5 puntos",
    minusTenPoints: "-10 puntos",
    scoringSubmitted: "✅ Puntuación enviada. Los jugadores en espera se unirán automáticamente después de pulsar Nueva ronda.",
    enterNameScoring: "Introduce tu nombre arriba para enviar la puntuación.",
    waitingForAllPlayers: "Esperando a todos los jugadores…",
    customCategoryPrefix: "Categoría propia",
    removeCustomCategory: "Eliminar categoría propia",
    addCustomCategory: "+ Añadir categoría propia",
    maxCustomCategories: "El máximo es de 5 categorías propias.",
    premiumLockedCategoryOfferIntro: "Al comprar una categoría ampliada, se desbloquea automáticamente la opción de elegir el número y el orden de las categorías con las que quieres jugar.",
    superPremiumUpsellBefore: "O compra",
    superPremiumLinkText: "Super Premium",
    superPremiumUpsellAfter: "y tendrás la opción de elegir el número y el orden de las categorías, todas las categorías ampliadas y 5 categorías propias.",
    changePlayerOnDevice: "Cambiar jugador en este dispositivo",
    waitingPlayerNextRound: "se unirá desde la siguiente ronda",
      freeLimitTitle: "Límite Free alcanzado",
      freeLimitText: "La versión Free incluye 3 rondas. Para continuar, pásate a Premium o elige ver un anuncio y desbloquear 3 rondas más.",
      freeUpgradeButton: "Obtener Premium",
      freeRewardButton: "Ver un anuncio y desbloquear 3 rondas más",
      backHome: "Volver a la página principal",
      freeRewardUnlocked: "✅ Se han desbloqueado 3 rondas más.",
      freeLimitReachedMessage: "Límite Free alcanzado. Elige Premium o un anuncio con recompensa para continuar.",
  },

  de: {
    room: "Raum",
    signedIn: "Angemeldet",
    notSignedIn: "Nicht angemeldet",
    bossRoom: "Du hast bezahlt – du bist der Chef dieses Raums!",
    likeApp: "Gefällt dir die App?",
    ratingUnavailable: "Die Bewertung ist verfügbar, sobald die App bei Google Play veröffentlicht wurde.",
    newGame: "Neues Spiel",
    rules: "Regeln",
    copyLink: "Link kopieren",
    share: "Teilen",
    disconnect: "Trennen",
    gameLanguage: "Spielsprache",
    diacriticsOptional: "Antworten sind auch ohne Sonderzeichen gültig.",
    joinGame: "Dem Spiel beitreten",
    yourName: "Dein Name",
    join: "Beitreten",
    startGame: "Spiel starten",
    gameSettings: "Spieleinstellungen",
    timeLimit: "Zeitlimit",
    noTimeLimit: "Kein Limit",
    roundCount: "Anzahl der Runden",
    unlimitedRounds: "Unbegrenzt",
    roundsCountSuffix: "Runden",
    gameSettingsSaveErrorPrefix: "❌ Spieleinstellungen speichern",
    availableLetters: "Verfügbare Buchstaben",
    players: "Spieler",
    waitingPlayers: "Wartende Spieler",
    roomCategories: "Raumkategorien",
    basicCategories: "Grundkategorien",
    extendedCategories: "Zusatzkategorien",
    customCategories: "Eigene Kategorien",
    categoryOrder: "Reihenfolge der Kategorien",
    playing: "Spiel läuft",
    drawAgain: "Erneut auslosen",
    scoring: "Auswertung",
    submitted: "Abgegeben",
    playersAnswers: "Antworten der Spieler",
    player: "Spieler",
    totalPoints: "Gesamtpunkte",
    round: "Runde",
    myScoring: "Meine Bewertung",
    submitScoring: "Bewertung absenden",
    newRound: "Neue Runde",
    finishGame: "Spiel beenden und Endergebnisse anzeigen",
    finalResults: "Endergebnisse",
    position: "Platz",
    gameFinishedMessage: "✅ Spiel beendet. Hier sind die Endergebnisse.",
    finishGameErrorPrefix: "❌ Spiel beenden",
    letterDrawn: "✅ Buchstabe ausgelost",
    drawingAgain: "… wird erneut ausgelost",
    drawingNextRound: "… Buchstabe für die nächste Runde wird ausgelost",
    drawingLetter: "… Buchstabe wird ausgelost",
    changePlayerAfterScoring: "Du kannst den Spieler erst wechseln, nachdem die Auswertung beendet ist.",
    changingPlayerErrorPrefix: "❌ Spieler wechseln",
    previousPlayerRemoved: "ℹ️ Der vorherige Spieler wurde von diesem Gerät entfernt. Gib einen anderen Namen ein.",
    disconnectedRoomCleared: "✅ getrennt, Raumdaten gelöscht",
    disconnected: "✅ getrennt",
    joinNameFirst: "❗ Tritt zuerst mit einem Namen bei.",
    savingScoresErrorPrefix: "❌ Punkte speichern",
    stopAfterFields: "Du kannst STOP drücken, nachdem du alle Felder ausgefüllt hast.",
    minTwoChars: "Jedes Feld muss mindestens zwei Zeichen enthalten.",
    mustStartWithLetter: "Jede Antwort muss mit dem ausgelosten Buchstaben beginnen.",
    waitingToJoin: "⏳ Du wartest auf den Beitritt. Du kommst ab der nächsten Runde ins Spiel.",
    enterNameAnswers: "Gib oben deinen Namen ein, um Antworten abzugeben.",
    statusSubmitted: " – abgegeben",
    statusWaiting: " – wartet",
    hideRoundHistory: "Rundenverlauf ausblenden",
    showRoundHistory: "Rundenverlauf anzeigen",
    noRoundScores: "Für diese Runde wurden noch keine Punkte gespeichert.",
    zeroPoints: "0 Punkte",
    fivePoints: "5 Punkte",
    tenPoints: "10 Punkte",
    minusFivePoints: "-5 Punkte",
    minusTenPoints: "-10 Punkte",
    scoringSubmitted: "✅ Bewertung abgegeben. Wartende Spieler treten nach dem Drücken von „Neue Runde“ automatisch bei.",
    enterNameScoring: "Gib oben deinen Namen ein, um die Bewertung abzugeben.",
    waitingForAllPlayers: "Warten auf alle Spieler…",
    customCategoryPrefix: "Eigene Kategorie",
    removeCustomCategory: "Eigene Kategorie entfernen",
    addCustomCategory: "+ Eigene Kategorie hinzufügen",
    maxCustomCategories: "Maximal 5 eigene Kategorien.",
    premiumLockedCategoryOfferIntro: "Beim Kauf einer Zusatzkategorie wird automatisch die Auswahl der Anzahl und Reihenfolge der Kategorien freigeschaltet.",
    superPremiumUpsellBefore: "Oder kaufe",
    superPremiumLinkText: "Super Premium",
    superPremiumUpsellAfter: "und erhalte die Auswahl von Anzahl und Reihenfolge der Kategorien, alle Zusatzkategorien sowie 5 eigene Kategorien.",
    changePlayerOnDevice: "Spieler auf diesem Gerät wechseln",
    waitingPlayerNextRound: "tritt ab der nächsten Runde bei",
    freeLimitTitle: "Free-Limit erreicht",
    freeLimitText: "Die Free-Version enthält 3 Runden. Um fortzufahren, wechsle zu Premium oder sieh dir eine Werbung an und schalte 3 weitere Runden frei.",
    freeUpgradeButton: "Premium holen",
    freeRewardButton: "Werbung ansehen und 3 weitere Runden freischalten",
    backHome: "Zur Startseite",
    freeRewardUnlocked: "✅ 3 weitere Runden wurden freigeschaltet.",
    freeLimitReachedMessage: "Free-Limit erreicht. Wähle Premium oder eine Werbung mit Belohnung, um fortzufahren.",
  },

  fr: {
    room: "Salle",
    signedIn: "Connecté",
    notSignedIn: "Non connecté",
    bossRoom: "Tu as payé, tu es donc le chef de cette salle !",
    likeApp: "Tu aimes l’application ?",
    ratingUnavailable: "L’évaluation sera disponible après la publication de l’application sur Google Play.",
    newGame: "Nouvelle partie",
    rules: "Règles",
    copyLink: "Copier le lien",
    share: "Partager",
    disconnect: "Se déconnecter",
    gameLanguage: "Langue du jeu",
    diacriticsOptional: "Les réponses sont valides même sans accents.",
    joinGame: "Rejoindre la partie",
    yourName: "Ton nom",
    join: "Rejoindre",
    startGame: "Démarrer la partie",
    gameSettings: "Paramètres de la partie",
    timeLimit: "Limite de temps",
    noTimeLimit: "Sans limite",
    roundCount: "Nombre de manches",
    unlimitedRounds: "Illimité",
    roundsCountSuffix: "manches",
    gameSettingsSaveErrorPrefix: "❌ paramètres de la partie",
    availableLetters: "Lettres disponibles",
    players: "Joueurs",
    waitingPlayers: "Joueurs en attente",
    roomCategories: "Catégories de la salle",
    basicCategories: "Catégories de base",
    extendedCategories: "Catégories supplémentaires",
    customCategories: "Catégories personnalisées",
    categoryOrder: "Ordre des catégories",
    playing: "Partie en cours",
    drawAgain: "Tirer à nouveau",
    scoring: "Évaluation",
    submitted: "Envoyé",
    playersAnswers: "Réponses des joueurs",
    player: "Joueur",
    totalPoints: "Total des points",
    round: "Manche",
    myScoring: "Mon évaluation",
    submitScoring: "Envoyer l’évaluation",
    newRound: "Nouvelle manche",
    finishGame: "Terminer la partie et afficher les résultats finaux",
    finalResults: "Résultats finaux",
    position: "Classement",
    gameFinishedMessage: "✅ Partie terminée. Voici les résultats finaux.",
    finishGameErrorPrefix: "❌ fin de la partie",
    letterDrawn: "✅ lettre tirée",
    drawingAgain: "… nouveau tirage",
    drawingNextRound: "… tirage d’une lettre pour la prochaine manche",
    drawingLetter: "… tirage d’une lettre",
    changePlayerAfterScoring: "Tu ne peux changer de joueur qu’après la fin de l’évaluation.",
    changingPlayerErrorPrefix: "❌ changement de joueur",
    previousPlayerRemoved: "ℹ️ Le joueur précédent a été retiré de cet appareil. Saisis un autre nom.",
    disconnectedRoomCleared: "✅ déconnecté, données de la salle effacées",
    disconnected: "✅ déconnecté",
    joinNameFirst: "❗ Rejoins d’abord la partie avec un nom.",
    savingScoresErrorPrefix: "❌ enregistrement des points",
    stopAfterFields: "Tu peux appuyer sur STOP après avoir rempli tous les champs.",
    minTwoChars: "Chaque champ doit contenir au moins deux caractères.",
    mustStartWithLetter: "Chaque réponse doit commencer par la lettre tirée.",
    waitingToJoin: "⏳ Tu attends de rejoindre la partie. Tu entreras en jeu à partir de la prochaine manche.",
    enterNameAnswers: "Saisis ton nom ci-dessus pour envoyer tes réponses.",
    statusSubmitted: " – envoyé",
    statusWaiting: " – en attente",
    hideRoundHistory: "Masquer l’historique des manches",
    showRoundHistory: "Afficher l’historique des manches",
    noRoundScores: "Aucun score de manche n’a encore été enregistré.",
    zeroPoints: "0 point",
    fivePoints: "5 points",
    tenPoints: "10 points",
    minusFivePoints: "-5 points",
    minusTenPoints: "-10 points",
    scoringSubmitted: "✅ Évaluation envoyée. Les joueurs en attente rejoindront automatiquement la partie après avoir appuyé sur « Nouvelle manche ».",
    enterNameScoring: "Saisis ton nom ci-dessus pour envoyer l’évaluation.",
    waitingForAllPlayers: "En attente de tous les joueurs…",
    customCategoryPrefix: "Catégorie personnalisée",
    removeCustomCategory: "Supprimer la catégorie personnalisée",
    addCustomCategory: "+ Ajouter une catégorie personnalisée",
    maxCustomCategories: "Le maximum est de 5 catégories personnalisées.",
    premiumLockedCategoryOfferIntro: "L’achat d’une catégorie supplémentaire déverrouille automatiquement le choix du nombre de catégories et de leur ordre.",
    superPremiumUpsellBefore: "Ou achète",
    superPremiumLinkText: "Super Premium",
    superPremiumUpsellAfter: "et tu obtiendras le choix du nombre et de l’ordre des catégories, toutes les catégories supplémentaires, ainsi que 5 catégories personnalisées.",
    changePlayerOnDevice: "Changer de joueur sur cet appareil",
    waitingPlayerNextRound: "rejoindra à partir de la prochaine manche",
    freeLimitTitle: "Limite Free atteinte",
    freeLimitText: "La version Free comprend 3 manches. Pour continuer, passe à Premium ou regarde une publicité afin de débloquer 3 manches supplémentaires.",
    freeUpgradeButton: "Passer à Premium",
    freeRewardButton: "Regarder une publicité et débloquer 3 manches supplémentaires",
    backHome: "Retour à l’accueil",
    freeRewardUnlocked: "✅ 3 manches supplémentaires sont débloquées.",
    freeLimitReachedMessage: "Limite Free atteinte. Choisis Premium ou une publicité récompensée pour continuer.",
  },

  "pt-BR": {
    room: "Sala",
    signedIn: "Conectado",
    notSignedIn: "Não conectado",
    bossRoom: "Você pagou, então é o chefe desta sala!",
    likeApp: "Você gostou do aplicativo?",
    ratingUnavailable: "A avaliação estará disponível depois que o aplicativo for publicado no Google Play.",
    newGame: "Novo jogo",
    rules: "Regras",
    copyLink: "Copiar link",
    share: "Compartilhar",
    disconnect: "Desconectar",
    gameLanguage: "Idioma do jogo",
    diacriticsOptional: "As respostas são válidas mesmo sem acentos.",
    joinGame: "Entrar no jogo",
    yourName: "Seu nome",
    join: "Entrar",
    startGame: "Iniciar jogo",
    gameSettings: "Configurações do jogo",
    timeLimit: "Limite de tempo",
    noTimeLimit: "Sem limite",
    roundCount: "Número de rodadas",
    unlimitedRounds: "Ilimitado",
    roundsCountSuffix: "rodadas",
    gameSettingsSaveErrorPrefix: "❌ configurações do jogo",
    availableLetters: "Letras disponíveis",
    players: "Jogadores",
    waitingPlayers: "Jogadores aguardando",
    roomCategories: "Categorias da sala",
    basicCategories: "Categorias básicas",
    extendedCategories: "Categorias adicionais",
    customCategories: "Categorias personalizadas",
    categoryOrder: "Ordem das categorias",
    playing: "Jogando",
    drawAgain: "Sortear novamente",
    scoring: "Pontuação",
    submitted: "Enviado",
    playersAnswers: "Respostas dos jogadores",
    player: "Jogador",
    totalPoints: "Total de pontos",
    round: "Rodada",
    myScoring: "Minha pontuação",
    submitScoring: "Enviar pontuação",
    newRound: "Nova rodada",
    finishGame: "Encerrar o jogo e mostrar o resultado final",
    finalResults: "Resultado final",
    position: "Posição",
    gameFinishedMessage: "✅ Jogo encerrado. Veja o resultado final.",
    finishGameErrorPrefix: "❌ encerrando o jogo",
    letterDrawn: "✅ letra sorteada",
    drawingAgain: "… sorteando novamente",
    drawingNextRound: "… sorteando uma letra para a próxima rodada",
    drawingLetter: "… sorteando uma letra",
    changePlayerAfterScoring: "Você só pode trocar de jogador depois que a pontuação for concluída.",
    changingPlayerErrorPrefix: "❌ trocando de jogador",
    previousPlayerRemoved: "ℹ️ O jogador anterior foi removido deste aparelho. Digite outro nome.",
    disconnectedRoomCleared: "✅ desconectado, dados da sala apagados",
    disconnected: "✅ desconectado",
    joinNameFirst: "❗ Primeiro entre com um nome.",
    savingScoresErrorPrefix: "❌ salvando pontuações",
    stopAfterFields: "Você pode apertar STOP depois de preencher todos os campos.",
    minTwoChars: "Cada campo deve conter pelo menos dois caracteres.",
    mustStartWithLetter: "Cada resposta deve começar com a letra sorteada.",
    waitingToJoin: "⏳ Você está aguardando para entrar. Participará do jogo a partir da próxima rodada.",
    enterNameAnswers: "Digite seu nome acima para enviar as respostas.",
    statusSubmitted: " – enviado",
    statusWaiting: " – aguardando",
    hideRoundHistory: "Ocultar histórico das rodadas",
    showRoundHistory: "Mostrar histórico das rodadas",
    noRoundScores: "Ainda não há pontuações salvas para esta rodada.",
    zeroPoints: "0 ponto",
    fivePoints: "5 pontos",
    tenPoints: "10 pontos",
    minusFivePoints: "-5 pontos",
    minusTenPoints: "-10 pontos",
    scoringSubmitted: "✅ Pontuação enviada. Os jogadores que estão aguardando entrarão automaticamente depois que você apertar Nova rodada.",
    enterNameScoring: "Digite seu nome acima para enviar a pontuação.",
    waitingForAllPlayers: "Aguardando todos os jogadores…",
    customCategoryPrefix: "Categoria personalizada",
    removeCustomCategory: "Remover categoria personalizada",
    addCustomCategory: "+ Adicionar categoria personalizada",
    maxCustomCategories: "O máximo é de 5 categorias personalizadas.",
    premiumLockedCategoryOfferIntro: "A compra de uma categoria adicional libera automaticamente a escolha da quantidade e da ordem das categorias.",
    superPremiumUpsellBefore: "Ou compre",
    superPremiumLinkText: "Super Premium",
    superPremiumUpsellAfter: "e tenha acesso à escolha da quantidade e da ordem das categorias, a todas as categorias adicionais e a 5 categorias personalizadas.",
    changePlayerOnDevice: "Trocar jogador neste aparelho",
    waitingPlayerNextRound: "entrará a partir da próxima rodada",
    freeLimitTitle: "Limite Free atingido",
    freeLimitText: "A versão Free inclui 3 rodadas. Para continuar, faça upgrade para Premium ou assista a um anúncio e libere mais 3 rodadas.",
    freeUpgradeButton: "Obter Premium",
    freeRewardButton: "Assistir a um anúncio e liberar mais 3 rodadas",
    backHome: "Voltar à página inicial",
    freeRewardUnlocked: "✅ Mais 3 rodadas foram liberadas.",
    freeLimitReachedMessage: "Limite Free atingido. Escolha Premium ou um anúncio com recompensa para continuar.",
  },
} as const;

export type UiTextKey = keyof typeof UI_TEXT.cs;

const TEXTS = UI_TEXT as unknown as Record<string, Record<UiTextKey, string>>;

export function getUiText(language: UiLanguage, key: UiTextKey) {
  return TEXTS[language]?.[key] ?? UI_TEXT.cs[key];
}

export const UI_RULES = {
  cs: {
    join: "Organizátor sdílí odkaz místnosti pomocí tlačítek Kopírovat odkaz nebo Sdílet. Ostatní hráči odkaz otevřou, zadají své jméno a připojí se do stejné místnosti.",
    play: "Hráči společně hrají na vylosované písmeno. Každý vyplní odpovědi do kategorií. Po vyplnění všech polí může hráč zmáčknout STOP. Každá odpověď musí začínat vylosovaným písmenem a mít alespoň dvě písmena. Na přeskočení do dalšího pole s odpovědí a finální STOP se dá použít ENTER na klávesnici.",
    scoringTitle: "Bodování",
    scoring: "Po STOPu všichni vidí odpovědi ostatních a bodují každou odpověď. 10 bodů za unikátní odpověď, 5 bodů za shodnou odpověď, 0 bodů za prázdnou odpověď. Lze použít i záporné body v případě neuznané odpovědi.",
  },
  en: {
    join: "The organiser shares the room link using the Copy link or Share button. Other players open the link, enter their name and join the same room.",
    play: "Everyone plays using the drawn letter and enters one answer for each category. Once all fields are completed, a player can press STOP. Every answer must begin with the drawn letter and contain at least two characters. ENTER can be used to move to the next answer field and to press the final STOP.",
    scoringTitle: "Scoring",
    scoring: "After STOP is pressed, everyone can see the other players’ answers and score each answer. 10 points for a unique answer, 5 points for a repeated answer, 0 points for an empty answer. Negative points can also be used for an invalid answer.",
  },
  es: {
    join: "El organizador comparte el enlace de la sala usando Copiar enlace o Compartir. Los demás jugadores abren el enlace, introducen su nombre y se unen a la misma sala.",
    play: "Todos juegan con la letra sorteada y escriben una respuesta para cada categoría. Cuando todos los campos están completos, un jugador puede pulsar STOP. Cada respuesta debe empezar con la letra sorteada y tener al menos dos caracteres. ENTER se puede usar para pasar al siguiente campo de respuesta y para pulsar el STOP final.",
    scoringTitle: "Puntuación",
    scoring: "Después de pulsar STOP, todos ven las respuestas de los demás y puntúan cada respuesta. 10 puntos por una respuesta única, 5 puntos por una respuesta repetida, 0 puntos por una respuesta vacía. También se pueden usar puntos negativos para una respuesta no aceptada.",
  },

  de: {
    join:
      "Der Organisator teilt den Raumlink über „Link kopieren“ oder „Teilen“. Die anderen Spieler öffnen den Link, geben ihren Namen ein und treten demselben Raum bei.",
    play:
      "Alle spielen mit dem ausgelosten Buchstaben und tragen für jede Kategorie eine Antwort ein. Sobald alle Felder ausgefüllt sind, kann ein Spieler STOP drücken. Jede Antwort muss mit dem ausgelosten Buchstaben beginnen und mindestens zwei Zeichen enthalten. Mit ENTER wechselst du zum nächsten Antwortfeld und kannst am Ende STOP drücken.",
    scoringTitle: "Auswertung",
    scoring:
      "Nachdem STOP gedrückt wurde, können alle die Antworten der anderen Spieler sehen und bewerten. 10 Punkte für eine einzigartige Antwort, 5 Punkte für eine doppelte Antwort und 0 Punkte für eine leere Antwort. Für eine ungültige Antwort können auch Minuspunkte vergeben werden.",
  },

  fr: {
    join:
      "L’organisateur partage le lien de la salle à l’aide des boutons « Copier le lien » ou « Partager ». Les autres joueurs ouvrent le lien, saisissent leur nom et rejoignent la même salle.",
    play:
      "Tout le monde joue avec la lettre tirée et saisit une réponse pour chaque catégorie. Une fois tous les champs remplis, un joueur peut appuyer sur STOP. Chaque réponse doit commencer par la lettre tirée et contenir au moins deux caractères. La touche ENTRÉE permet de passer au champ suivant et d’appuyer sur STOP après le dernier champ.",
    scoringTitle: "Évaluation",
    scoring:
      "Après avoir appuyé sur STOP, chacun peut voir les réponses des autres joueurs et les évaluer. 10 points pour une réponse unique, 5 points pour une réponse identique à celle d’un autre joueur et 0 point pour une réponse vide. Des points négatifs peuvent également être attribués à une réponse non valide.",
  },

  "pt-BR": {
    join:
      "O organizador compartilha o link da sala usando os botões “Copiar link” ou “Compartilhar”. Os outros jogadores abrem o link, digitam seus nomes e entram na mesma sala.",
    play:
      "Todos jogam com a letra sorteada e digitam uma resposta para cada categoria. Depois de preencher todos os campos, um jogador pode apertar STOP. Cada resposta deve começar com a letra sorteada e ter pelo menos dois caracteres. A tecla ENTER pode ser usada para avançar para o próximo campo e apertar STOP no final.",
    scoringTitle: "Pontuação",
    scoring:
      "Depois que STOP for apertado, todos podem ver as respostas dos outros jogadores e atribuir pontos. São 10 pontos para uma resposta única, 5 pontos para uma resposta repetida e 0 ponto para uma resposta vazia. Também podem ser usados pontos negativos para uma resposta inválida.",
  },
} as const;

const RULES = UI_RULES as unknown as Record<string, typeof UI_RULES.cs>;

export function getUiRules(language: UiLanguage) {
  return RULES[language] ?? UI_RULES.cs;
}

const ROOM_FULL_MESSAGES: Record<
  UiLanguage,
  (maxPlayers: number) => string
> = {
  cs: (maxPlayers) =>
    `❌ Místnost je plná. Free verze umožňuje max. ${maxPlayers} hráče. Pro více hráčů si kup Premium. Víc hráčů, větší zábava! :-)`,
  en: (maxPlayers) =>
    `❌ This room is full. The Free version allows up to ${maxPlayers} players. Upgrade to Premium for more players. More players, more fun! :-)`,
  es: (maxPlayers) =>
    `❌ La sala está llena. La versión Free permite hasta ${maxPlayers} jugadores. Compra Premium para más jugadores. Más jugadores, más diversión. :-)`,

  de: (maxPlayers) =>
    `❌ Dieser Raum ist voll. Die Free-Version erlaubt höchstens ${maxPlayers} Spieler. Hol dir Premium für mehr Spieler. Mehr Spieler, mehr Spaß! :-)`,

  fr: (maxPlayers) =>
    `❌ Cette salle est pleine. La version Free permet jusqu’à ${maxPlayers} joueurs. Passe à Premium pour accueillir plus de joueurs. Plus on est nombreux, plus on s’amuse ! :-)`,

  "pt-BR": (maxPlayers) =>
    `❌ Esta sala está cheia. A versão Free permite até ${maxPlayers} jogadores. Faça upgrade para Premium para jogar com mais pessoas. Mais jogadores, mais diversão! :-)`,
};

const STOP_PRESSED_MESSAGES: Record<
  UiLanguage,
  (name: string) => string
> = {
  cs: (name) => `✅ STOP stiskl ${name}`,
  en: (name) => `✅ STOP pressed by ${name}`,
  es: (name) => `✅ ${name} pulsó STOP`,

  de: (name) => `✅ ${name} hat STOP gedrückt`,

  fr: (name) => `✅ ${name} a appuyé sur STOP`,

  "pt-BR": (name) => `✅ ${name} apertou STOP`,
};

const CATEGORY_HELP_TEXT = {
  cs: {
    player:
      "Kategorie vybírá organizátor místnosti. Ty vidíš aktuální výběr a můžeš mu radit, co upravit.",
    premiumOrganizer:
      "Premium: základní kategorie jsou pevně dané. Rozšířené kategorie jsou zamčené. Po dokoupení alespoň jedné rozšířené kategorie se odemkne volba počtu kategorií a jejich pořadí.",
    superPremiumOrganizer:
      "Super Premium: vyber základní i rozšířené kategorie. Můžeš měnit pořadí a používat vlastní kategorie.",
  },
  en: {
    player:
      "The organiser chooses the room categories. You can see the current selection and suggest changes.",
    premiumOrganizer:
      "Premium: the basic categories are fixed. Extended categories are locked. Buying at least one extended category unlocks category selection and ordering.",
    superPremiumOrganizer:
      "Super Premium: choose basic and extended categories, change their order and add custom categories.",
  },
  es: {
    player:
      "El organizador elige las categorías de la sala. Tú ves la selección actual y puedes sugerir cambios.",
    premiumOrganizer:
      "Premium: las categorías básicas son fijas. Las categorías ampliadas están bloqueadas. Al comprar al menos una categoría ampliada se desbloquea la selección y el orden de categorías.",
    superPremiumOrganizer:
      "Super Premium: elige categorías básicas y ampliadas, cambia su orden y añade categorías propias.",
  },

  de: {
    player:
      "Der Organisator wählt die Kategorien des Raums aus. Du kannst die aktuelle Auswahl sehen und Änderungen vorschlagen.",
    premiumOrganizer:
      "Premium: Die Grundkategorien sind festgelegt. Zusatzkategorien sind gesperrt. Der Kauf mindestens einer Zusatzkategorie schaltet die Auswahl und Reihenfolge der Kategorien frei.",
    superPremiumOrganizer:
      "Super Premium: Wähle Grund- und Zusatzkategorien aus, ändere ihre Reihenfolge und füge eigene Kategorien hinzu.",
  },

  fr: {
    player:
      "L’organisateur choisit les catégories de la salle. Tu peux voir la sélection actuelle et lui suggérer des modifications.",
    premiumOrganizer:
      "Premium : les catégories de base sont fixes. Les catégories supplémentaires sont verrouillées. L’achat d’au moins une catégorie supplémentaire déverrouille la sélection et l’ordre des catégories.",
    superPremiumOrganizer:
      "Super Premium : choisis les catégories de base et supplémentaires, modifie leur ordre et ajoute des catégories personnalisées.",
  },

  "pt-BR": {
    player:
      "O organizador escolhe as categorias da sala. Você pode ver a seleção atual e sugerir alterações.",
    premiumOrganizer:
      "Premium: as categorias básicas são fixas. As categorias adicionais ficam bloqueadas. A compra de pelo menos uma categoria adicional libera a seleção e a ordem das categorias.",
    superPremiumOrganizer:
      "Super Premium: escolha categorias básicas e adicionais, altere a ordem e adicione categorias personalizadas.",
  },
};

export function roomFullMessage(
  language: UiLanguage,
  maxPlayers: number
) {
  return ROOM_FULL_MESSAGES[language](maxPlayers);
}

export function stopPressedMessage(
  language: UiLanguage,
  name: string
) {
  return STOP_PRESSED_MESSAGES[language](name);
}

const GAME_LANGUAGE_NAMES: Record<
  UiLanguage,
  Record<GameLanguage, string>
> = {
  cs: {
    cs: "Čeština",
    en: "Angličtina",
    es: "Španělština",
    de: "Němčina",
    fr: "Francouzština",
    "pt-BR": "Brazilská portugalština",
    id: "Indonéština",
    tr: "Turečtina",
    pl: "Polština",
    it: "Italština",
  },
  en: {
    cs: "Czech",
    en: "English",
    es: "Spanish",
    de: "German",
    fr: "French",
    "pt-BR": "Brazilian Portuguese",
    id: "Indonesian",
    tr: "Turkish",
    pl: "Polish",
    it: "Italian",
  },
  es: {
    cs: "Checo",
    en: "Inglés",
    es: "Español",
    de: "Alemán",
    fr: "Francés",
    "pt-BR": "Portugués de Brasil",
    id: "Indonesio",
    tr: "Turco",
    pl: "Polaco",
    it: "Italiano",
  },

  de: {
    cs: "Tschechisch",
    en: "Englisch",
    es: "Spanisch",
    de: "Deutsch",
    fr: "Französisch",
    "pt-BR": "Brasilianisches Portugiesisch",
    id: "Indonesisch",
    tr: "Türkisch",
    pl: "Polnisch",
    it: "Italienisch",
  },

  fr: {
    cs: "Tchèque",
    en: "Anglais",
    es: "Espagnol",
    de: "Allemand",
    fr: "Français",
    "pt-BR": "Portugais du Brésil",
    id: "Indonésien",
    tr: "Turc",
    pl: "Polonais",
    it: "Italien",
  },

  "pt-BR": {
    cs: "Tcheco",
    en: "Inglês",
    es: "Espanhol",
    de: "Alemão",
    fr: "Francês",
    "pt-BR": "Português do Brasil",
    id: "Indonésio",
    tr: "Turco",
    pl: "Polonês",
    it: "Italiano",
  },
};

const GAME_LANGUAGE_INSTRUCTIONS: Record<
  UiLanguage,
  Record<GameLanguage, string>
> = {
  cs: {
    cs: "Všechny odpovědi piš česky.",
    en: "Všechny odpovědi piš anglicky.",
    es: "Všechny odpovědi piš španělsky.",
    de: "Všechny odpovědi piš německy.",
    fr: "Všechny odpovědi piš francouzsky.",
    "pt-BR": "Všechny odpovědi piš brazilskou portugalštinou.",
    id: "Všechny odpovědi piš indonésky.",
    tr: "Všechny odpovědi piš turecky.",
    pl: "Všechny odpovědi piš polsky.",
    it: "Všechny odpovědi piš italsky.",
  },
  en: {
    cs: "Write all answers in Czech.",
    en: "Write all answers in English.",
    es: "Write all answers in Spanish.",
    de: "Write all answers in German.",
    fr: "Write all answers in French.",
    "pt-BR": "Write all answers in Brazilian Portuguese.",
    id: "Write all answers in Indonesian.",
    tr: "Write all answers in Turkish.",
    pl: "Write all answers in Polish.",
    it: "Write all answers in Italian.",
  },
  es: {
    cs: "Escribe todas las respuestas en checo.",
    en: "Escribe todas las respuestas en inglés.",
    es: "Escribe todas las respuestas en español.",
    de: "Escribe todas las respuestas en alemán.",
    fr: "Escribe todas las respuestas en francés.",
    "pt-BR": "Escribe todas las respuestas en portugués de Brasil.",
    id: "Escribe todas las respuestas en indonesio.",
    tr: "Escribe todas las respuestas en turco.",
    pl: "Escribe todas las respuestas en polaco.",
    it: "Escribe todas las respuestas en italiano.",
  },

  de: {
    cs: "Schreibe alle Antworten auf Tschechisch.",
    en: "Schreibe alle Antworten auf Englisch.",
    es: "Schreibe alle Antworten auf Spanisch.",
    de: "Schreibe alle Antworten auf Deutsch.",
    fr: "Schreibe alle Antworten auf Französisch.",
    "pt-BR": "Schreibe alle Antworten auf brasilianischem Portugiesisch.",
    id: "Schreibe alle Antworten auf Indonesisch.",
    tr: "Schreibe alle Antworten auf Türkisch.",
    pl: "Schreibe alle Antworten auf Polnisch.",
    it: "Schreibe alle Antworten auf Italienisch.",
  },

  fr: {
    cs: "Écris toutes les réponses en tchèque.",
    en: "Écris toutes les réponses en anglais.",
    es: "Écris toutes les réponses en espagnol.",
    de: "Écris toutes les réponses en allemand.",
    fr: "Écris toutes les réponses en français.",
    "pt-BR": "Écris toutes les réponses en portugais du Brésil.",
    id: "Écris toutes les réponses en indonésien.",
    tr: "Écris toutes les réponses en turc.",
    pl: "Écris toutes les réponses en polonais.",
    it: "Écris toutes les réponses en italien.",
  },

  "pt-BR": {
    cs: "Escreva todas as respostas em tcheco.",
    en: "Escreva todas as respostas em inglês.",
    es: "Escreva todas as respostas em espanhol.",
    de: "Escreva todas as respostas em alemão.",
    fr: "Escreva todas as respostas em francês.",
    "pt-BR": "Escreva todas as respostas em português do Brasil.",
    id: "Escreva todas as respostas em indonésio.",
    tr: "Escreva todas as respostas em turco.",
    pl: "Escreva todas as respostas em polonês.",
    it: "Escreva todas as respostas em italiano.",
  },
};

export function gameLanguageNameText(
  uiLanguage: UiLanguage,
  roomLanguage: GameLanguage
) {
  return GAME_LANGUAGE_NAMES[uiLanguage][roomLanguage];
}

export function gameLanguageInstructionText(
  uiLanguage: UiLanguage,
  roomLanguage: GameLanguage
) {
  return GAME_LANGUAGE_INSTRUCTIONS[uiLanguage][roomLanguage];
}

export function categoryHelpText(
  language: UiLanguage,
  isOrganizer: boolean,
  roomTier: RoomTier
) {
  const texts = CATEGORY_HELP_TEXT[language];

  if (!isOrganizer) return texts.player;

  return roomTier === "premium"
    ? texts.premiumOrganizer
    : texts.superPremiumOrganizer;
}
