
alter table public.players
  add column if not exists device_id uuid;

create index if not exists players_room_device_id_idx
  on public.players (room_id, device_id);

create table if not exists public.coin_wallets (
  device_id uuid primary key,
  secret_hash text not null,
  balance integer not null default 0 check (balance >= 0),
  qualifying_rounds integer not null default 0 check (qualifying_rounds >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.coin_unlocks (
  device_id uuid not null references public.coin_wallets(device_id) on delete cascade,
  unlock_key text not null,
  cost integer not null check (cost > 0),
  unlocked_at timestamptz not null default now(),
  primary key (device_id, unlock_key)
);

create table if not exists public.round_participants (
  round_id uuid not null references public.rounds(id) on delete cascade,
  player_id uuid not null,
  device_id uuid,
  primary key (round_id, player_id)
);

create index if not exists round_participants_round_device_idx
  on public.round_participants (round_id, device_id);

create table if not exists public.coin_round_rewards (
  round_id uuid primary key references public.rounds(id) on delete cascade,
  room_id uuid not null references public.rooms(id) on delete cascade,
  device_id uuid not null references public.coin_wallets(device_id) on delete cascade,
  coins integer not null default 2 check (coins > 0),
  awarded_at timestamptz not null default now()
);

create table if not exists public.coin_ledger (
  id bigint generated by default as identity primary key,
  device_id uuid not null references public.coin_wallets(device_id) on delete cascade,
  delta integer not null,
  reason text not null,
  room_id uuid references public.rooms(id) on delete set null,
  round_id uuid references public.rounds(id) on delete set null,
  unlock_key text,
  created_at timestamptz not null default now()
);

alter table public.coin_wallets enable row level security;
alter table public.coin_unlocks enable row level security;
alter table public.round_participants enable row level security;
alter table public.coin_round_rewards enable row level security;
alter table public.coin_ledger enable row level security;

revoke all on table public.coin_wallets from public, anon, authenticated;
revoke all on table public.coin_unlocks from public, anon, authenticated;
revoke all on table public.round_participants from public, anon, authenticated;
revoke all on table public.coin_round_rewards from public, anon, authenticated;
revoke all on table public.coin_ledger from public, anon, authenticated;

create schema if not exists private;

create or replace function private.zm_coin_secret_hash(p_secret text)
returns text
language sql
immutable
strict
set search_path = pg_catalog, extensions
as $$
  select encode(extensions.digest(p_secret, 'sha256'), 'hex');
$$;

create or replace function private.zm_coin_unlock_cost(p_unlock_key text)
returns integer
language sql
immutable
strict
set search_path = pg_catalog
as $$
  select case p_unlock_key
    when 'category_actor' then 250
    when 'category_music' then 250
    when 'category_river_mountain' then 250
    when 'category_job' then 250
    when 'category_color' then 250
    when 'feature_category_order' then 350
    when 'feature_round_count' then 450
    when 'feature_round_time' then 550
    when 'feature_custom_categories' then 750
    else null
  end;
$$;

create or replace function private.zm_coin_wallet_json(
  p_device_id uuid,
  p_awarded boolean default false,
  p_reason text default null
)
returns jsonb
language sql
stable
security definer
set search_path = public, pg_catalog
as $$
  select jsonb_build_object(
    'balance', w.balance,
    'qualifying_rounds', w.qualifying_rounds,
    'unlocks', coalesce(
      (
        select jsonb_agg(u.unlock_key order by u.unlock_key)
        from public.coin_unlocks u
        where u.device_id = w.device_id
      ),
      '[]'::jsonb
    ),
    'awarded', p_awarded,
    'reason', p_reason
  )
  from public.coin_wallets w
  where w.device_id = p_device_id;
$$;

create or replace function private.zm_snapshot_round_participants()
returns trigger
language plpgsql
security definer
set search_path = public, pg_catalog
as $$
begin
  insert into public.round_participants(round_id, player_id, device_id)
  select new.id, p.id, p.device_id
  from public.players p
  where p.room_id = new.room_id
    and p.status = 'active'
  on conflict (round_id, player_id) do nothing;

  return new;
end;
$$;

drop trigger if exists rounds_snapshot_participants on public.rounds;
create trigger rounds_snapshot_participants
after insert on public.rounds
for each row
execute function private.zm_snapshot_round_participants();

create or replace function public.get_coin_wallet_state(
  p_device_id uuid,
  p_device_secret text
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, extensions, pg_catalog
as $$
declare
  v_hash text;
  v_existing_hash text;
begin
  if p_device_id is null or p_device_secret is null or length(p_device_secret) < 16 then
    raise exception 'Invalid coin identity';
  end if;

  v_hash := private.zm_coin_secret_hash(p_device_secret);

  insert into public.coin_wallets(device_id, secret_hash)
  values (p_device_id, v_hash)
  on conflict (device_id) do nothing;

  select secret_hash into v_existing_hash
  from public.coin_wallets
  where device_id = p_device_id;

  if v_existing_hash is distinct from v_hash then
    raise exception 'Coin identity mismatch';
  end if;

  return private.zm_coin_wallet_json(p_device_id, false, null);
end;
$$;

create or replace function public.purchase_coin_unlock(
  p_device_id uuid,
  p_device_secret text,
  p_unlock_key text
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, extensions, pg_catalog
as $$
declare
  v_hash text;
  v_cost integer;
  v_balance integer;
begin
  v_cost := private.zm_coin_unlock_cost(p_unlock_key);
  if v_cost is null then
    raise exception 'Unknown coin unlock';
  end if;

  v_hash := private.zm_coin_secret_hash(p_device_secret);

  perform 1
  from public.coin_wallets
  where device_id = p_device_id
    and secret_hash = v_hash
  for update;

  if not found then
    raise exception 'Coin identity mismatch';
  end if;

  if exists (
    select 1 from public.coin_unlocks
    where device_id = p_device_id
      and unlock_key = p_unlock_key
  ) then
    return private.zm_coin_wallet_json(p_device_id, false, 'already_unlocked');
  end if;

  select balance into v_balance
  from public.coin_wallets
  where device_id = p_device_id;

  if v_balance < v_cost then
    return private.zm_coin_wallet_json(p_device_id, false, 'insufficient_coins');
  end if;

  update public.coin_wallets
  set balance = balance - v_cost,
      updated_at = now()
  where device_id = p_device_id;

  insert into public.coin_unlocks(device_id, unlock_key, cost)
  values (p_device_id, p_unlock_key, v_cost);

  insert into public.coin_ledger(device_id, delta, reason, unlock_key)
  values (p_device_id, -v_cost, 'unlock_purchase', p_unlock_key);

  return private.zm_coin_wallet_json(p_device_id, false, 'purchased');
end;
$$;

create or replace function public.claim_coin_round_reward(
  p_room_id uuid,
  p_round_id uuid,
  p_creator_token text,
  p_device_id uuid,
  p_device_secret text
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, extensions, pg_catalog
as $$
declare
  v_hash text;
  v_room public.rooms%rowtype;
  v_round public.rounds%rowtype;
  v_device_count integer;
  v_category_count integer;
  v_inserted integer;
begin
  v_hash := private.zm_coin_secret_hash(p_device_secret);

  perform 1
  from public.coin_wallets
  where device_id = p_device_id
    and secret_hash = v_hash
  for update;

  if not found then
    raise exception 'Coin identity mismatch';
  end if;

  select * into v_room
  from public.rooms
  where id = p_room_id;

  if not found
     or v_room.creator_tier <> 'super_premium'
     or v_room.letter_deck_owner_id is distinct from p_device_id
     or p_creator_token is null
     or p_creator_token = ''
     or not (
       (v_room.creator_token_hash is not null
        and v_room.creator_token_hash = encode(extensions.digest(p_creator_token, 'sha256'), 'hex'))
       or
       (v_room.creator_token is not null
        and v_room.creator_token = p_creator_token)
     )
  then
    raise exception 'Organizer authorization required';
  end if;

  select * into v_round
  from public.rounds
  where id = p_round_id
    and room_id = p_room_id
    and status in ('scoring', 'done');

  if not found then
    return private.zm_coin_wallet_json(p_device_id, false, 'round_not_ready');
  end if;

  if exists (
    select 1 from public.coin_round_rewards
    where round_id = p_round_id
  ) then
    return private.zm_coin_wallet_json(p_device_id, false, 'already_awarded');
  end if;

  select count(distinct rp.device_id)
  into v_device_count
  from public.round_participants rp
  where rp.round_id = p_round_id
    and rp.device_id is not null;

  if coalesce(v_device_count, 0) < 2 then
    return private.zm_coin_wallet_json(p_device_id, false, 'not_enough_devices');
  end if;

  v_category_count := jsonb_array_length(v_round.categories);

  if v_category_count <= 0 then
    return private.zm_coin_wallet_json(p_device_id, false, 'round_not_ready');
  end if;

  if exists (
    select 1
    from public.round_participants rp
    where rp.round_id = p_round_id
      and (
        select count(distinct s.category)
        from public.scores s
        where s.room_id = p_room_id
          and s.player_id = rp.player_id
          and s.round = v_round.round_no
          and s.category in (
            select jsonb_array_elements_text(v_round.categories)
          )
      ) < v_category_count
  ) then
    return private.zm_coin_wallet_json(p_device_id, false, 'round_not_ready');
  end if;

  insert into public.coin_round_rewards(round_id, room_id, device_id, coins)
  values (p_round_id, p_room_id, p_device_id, 2)
  on conflict (round_id) do nothing;

  get diagnostics v_inserted = row_count;

  if v_inserted = 0 then
    return private.zm_coin_wallet_json(p_device_id, false, 'already_awarded');
  end if;

  update public.coin_wallets
  set balance = balance + 2,
      qualifying_rounds = qualifying_rounds + 1,
      updated_at = now()
  where device_id = p_device_id;

  insert into public.coin_ledger(device_id, delta, reason, room_id, round_id)
  values (p_device_id, 2, 'qualifying_round', p_room_id, p_round_id);

  return private.zm_coin_wallet_json(p_device_id, true, 'awarded');
end;
$$;

revoke all on function public.get_coin_wallet_state(uuid, text) from public;
revoke all on function public.purchase_coin_unlock(uuid, text, text) from public;
revoke all on function public.claim_coin_round_reward(uuid, uuid, text, uuid, text) from public;

grant execute on function public.get_coin_wallet_state(uuid, text) to anon, authenticated;
grant execute on function public.purchase_coin_unlock(uuid, text, text) to anon, authenticated;
grant execute on function public.claim_coin_round_reward(uuid, uuid, text, uuid, text) to anon, authenticated;
